"""dmdt-gis — GIS layer for the Delhi Metro Digital Twin."""

from __future__ import annotations

from .crs import UTM43N, WEB_MERCATOR, WGS84, lonlat_to_utm, transformer, utm_to_lonlat
from .dataset import (
    DATA_FILE,
    DepotSpec,
    LineSpec,
    Network,
    StationSpec,
    load_network,
)
from .geometry import (
    Curvature,
    bearing_deg,
    bounding_box,
    curvature_radius_m,
    envelope_of,
    haversine_m,
    max_curvature_segment,
    offset_linestring_m,
    planar_distance_m,
    platform_polygon_m,
    polyline_length_m,
    station_polygon_m,
    turning_deg,
)
from .spatial import (
    CrossoverGeometry,
    DepotGeometry,
    JunctionGeometry,
    PlatformGeometry,
    SidingGeometry,
    StationGeometry,
    SwitchGeometry,
    TrackGeometry,
    build_all_crossover_geometries,
    build_all_depot_geometries,
    build_all_junction_geometries,
    build_all_platform_geometries,
    build_all_station_geometries,
    build_all_track_geometries,
)
from .track import TrackBuilder, TrackSegmentGeometry, design_speed_kmh
from .validation import (
    ValidationResult,
    validate_all_track_segments,
    validate_coordinate,
    validate_depot,
    validate_full_network,
    validate_geometry_layer,
    validate_line,
    validate_network,
    validate_platform_polygon,
    validate_station,
    validate_station_polygon,
    validate_track_segment,
)
from .wkb import ensure_valid, from_wkb_hex, from_wkt, to_wkb_hex, to_wkt

__all__ = [
    "DATA_FILE",
    "DepotSpec",
    "LineSpec",
    "Network",
    "StationSpec",
    "load_network",
    "WGS84",
    "UTM43N",
    "WEB_MERCATOR",
    "transformer",
    "lonlat_to_utm",
    "utm_to_lonlat",
    "Curvature",
    "bearing_deg",
    "turning_deg",
    "haversine_m",
    "planar_distance_m",
    "polyline_length_m",
    "curvature_radius_m",
    "max_curvature_segment",
    "offset_linestring_m",
    "station_polygon_m",
    "platform_polygon_m",
    "bounding_box",
    "envelope_of",
    "TrackBuilder",
    "TrackSegmentGeometry",
    "design_speed_kmh",
    "to_wkb_hex",
    "from_wkb_hex",
    "to_wkt",
    "from_wkt",
    "ensure_valid",
    "ValidationResult",
    "validate_coordinate",
    "validate_station",
    "validate_depot",
    "validate_line",
    "validate_network",
    "validate_station_polygon",
    "validate_platform_polygon",
    "validate_track_segment",
    "validate_all_track_segments",
    "validate_geometry_layer",
    "validate_full_network",
    "StationGeometry",
    "PlatformGeometry",
    "TrackGeometry",
    "DepotGeometry",
    "SidingGeometry",
    "JunctionGeometry",
    "CrossoverGeometry",
    "SwitchGeometry",
    "build_all_station_geometries",
    "build_all_platform_geometries",
    "build_all_track_geometries",
    "build_all_depot_geometries",
    "build_all_junction_geometries",
    "build_all_crossover_geometries",
]

__version__ = "0.1.0"
